# Generated by Django 6.0.6 on 2026-07-03 01:37

from django.db import migrations, models

import game.models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogador",
            name="foto",
            field=models.ImageField(upload_to="fotos_jogadores/%Y/%m/%d/", validators=[game.models.validar_tamanho_imagem], verbose_name="Foto do Jogador"),
        ),
    ]
