# Generated by Django 6.0.6 on 2026-07-06 15:39

from django.db import migrations, models

import game.models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_jogador_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogador",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_jogadores/%Y/%m/%d/", validators=[game.models.validar_tamanho_imagem], verbose_name="Foto do Jogador"),
        ),
    ]
